language: node_js
node_js:
- stable
npm: true
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: dJEyx83QwMtzVUGVvqAUEazRl5+8i34lBly6ABkUCVjoVopdpN2lGwUYkYm4Z4GsqPY/XTEBeLuFx9LZ8lI1KqaZwKDkxm78SE7+2TzDHVASLbBNrJ8RCd/GKxW22DM9j+xUrihomIF9nqvFE440Zw7LgxvIOSwgFzQbTRbFuePUKHe0iiBH7QdZGVm59PfP5AtKLKCTlTrx2yzVla9T4BhlpPslBkWGmuhAuti7Ho6Bg9V1v4mVOHmAmaplxTi8pdTKw9xj8PSYKkbJy30Mwh1XeKcJEpfscjoRkQXNQheLbDVtMH68//7Trxw3O3K0Wx79+aDtOhXDVB2ZJchw/6ASWW959JQbj7S/6vlvwtL6wSjkBhi4A3J+8C5CAuqt9+Inxe4lCFfFQ90gYtLleGv191Rh0eYMZBC/kRbU5ZG/963Ysqbe6R+1ZqfbBbrCpyJntZXwZLcc57VOTeVYF51ppY4i4mPVS/MJJ0mT3a+TuzzzoO+pr0oGeHiMXjm8HANwxk87cfHvhtsF/sQ8b173M5GV6aILciFArZwjknDMMabWMI9TJ7Bh38EPuDO1e1+ygUqRez+OPSd33TfJqU2VhbXa4SHugCJeL4Gi12lTsP1kjIGjThIlmLpyV11CpzfYfxSXVe/KjwXfSfuoz6fc+XERG4ybLS9WFoQl4Bw=
  app: stormy-springs-60842
  on:
    all_branches: 'true'
    repo: Mcilhaggis/lets-go-travel-planner
  skip_cleanup: 'true'
