language: node_js
branches:
  only:
  - master
node_js:
- stable
npm: true
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: Y0wjvwshgVKKhfGuo/QygmjL0Tg8quKMzD/KnO6ZHa4hOnqbxv8mEuKsihN0W/MOAFA6OdTEXO+wWXoizS0mdBW337G/QveurzPhJP95+4YVlOz0bibhidVKdKbcF7LNUgICZfNvZR8E4LW/RupqGwMLKw/wK3K3zfYK9D9kERY6Y8PVthk8zdlpNLcGP004GdtCqy/rZUn3abSAXv0cQm6BMOcfGcZNbChXYVkAg4Vb4Y6SWXeBcZAVbCVKDrS2Eum+vtdJcBKByMJBWd2U0uGvpF/MoaemWqvalBPLybtaecFLpIrZbvnDUKppfYR+yxpMQ5IRKmoxhJN75XIdh8vSuzB0Ncvo1T2+8caue5BJP46wvCPk1xoSgEajTLwASlxVeeNCi47sYUBTrheWnfJwjMgfvXvW12rbi1KlmSFuMdHwTCosISguh9qNnonL4ZRwnq+v2c9Z5SjL9yOaQcS0tnp6l9g8uf4Wo0CnaBQphzlNQcR4ngbLAc87ORqrZGlsKUalgGtV4bTxr3W9mUEnlOx/bg+P4Ih64q/QP8yiLiYTDyJq5q1LrO4cdD/LicOp1NncxMqwnav+Ux94yZ9L5H38+7ExFEkVMJwSlIrebAMwOcxpq6ughJeJj6ZW6HkaBWGOOnLjXU8hUEVVUApdPrdF1ToWmV0E0gwIfmQ=
  app: stormy-springs-60842
  on:
    repo: Mcilhaggis/lets-go-travel-planner
  skip_cleanup: 'true'
